repos:
  - repo: local
    hooks:
      - id: make-format-and-check
        name: Validar Calidad (Formateo y Linter)...
        # Aplicamos el formato, luego nos fijamos si el codigo es bueno y luego limpiamos los residuos
        entry: make format check clean
        language: system
        pass_filenames: false
        always_run: true
  
  - repo: https://github.com/crate-ci/typos
    rev: v1.50.2
    hooks:
      - id: typos
        exclude: ^wyrm_core/.*\.o$