# Este archivo nos ayuda a lidiar con los errores de typs, como el linter no distigue idiomas debemos aclarar algunas

[default.extend-words]

# Falsos positivos del español frente al inglés
problema = "problema"
problemas = "problemas"
producto = "producto"
productos = "productos"
comando = "comando"
comandos = "comandos"
programa = "programa"
programas = "programas"
dependencias = "dependencias"
dependencia = "dependencia"
argumentos = "argumentos"
argumento = "argumento"
hace = "hace"
dragon = "dragón"
dragones = "dragones"
combinacion = "combinación"
combinaciones = "combinaciónes"
componente = "componente"   
componentes = "componentes"
ser = "ser"
conclusiones = "conclusiones"
conclusion = "conclusión"
referentes = "referentes"
referente = "referente"
ende = "ende"
representacion = "representación"
representaciones = "representaciones"
aspectos = "aspectos"
aspecto = "aspecto"
posible = "posible"
varios = "varios"
multiplicacion = "multiplicación"
importante = "importante"
importantes = "importantes"
funcion = "función"
funciones = "funciones"
declaracion = "declaración"
declaraciones = "declaraciones"
definicion = "definición"
definiciones = "definiciones"
criticos = "criticos"
criticas = "criticas"
implementacion = "implementación"
implementaciones = "implementaciones"
despide = "despide"
interprete = "intérprete"
doble = "doble"
dobles = "dobles"
responsable = "responsable"
responsables = "responsables"
compilacion = "compilación"
compilaciones = "compilaciones"
contendor = "contendor"
contendores = "contendores"
responde = "responde"
inicial = "inicial"
historial = "historial"
instale = "instalé"
fase = "fase"
fases = "fases"
simular = "simular"
expresion = "expresión"
funcional = "funcional"
interpretarse = "interpretarse"
excede = "excede"
momento = "momento"
pase = "pase"
falso = "falso"

# Jerga técnica de Wyrm
wyrm = "wyrm"
unmut = "unmut"